set(LOGGER_DEPS_DIR ${CMAKE_SOURCE_DIR}/deps/logger)
configure_file(cmake/in/gitignore.in ${LOGGER_DEPS_DIR}/.gitignore COPYONLY)
execute_process(COMMAND ${CMAKE_COMMAND} -G "${CMAKE_GENERATOR}" . WORKING_DIRECTORY ${LOGGER_DEPS_DIR})
execute_process(COMMAND ${CMAKE_COMMAND} --build . WORKING_DIRECTORY ${LOGGER_DEPS_DIR})
find_library(logger NAMES logger.a logger PATHS ${LOGGER_DEPS_DIR} PATH_SUFFIXES lib Release NO_DEFAULT_PATH)
include_directories(${LOGGER_DEPS_DIR}/include)