set(LMDB_DEPS_DIR ${CMAKE_SOURCE_DIR}/deps/lmdb)
set(LMDB_SOURCE_DIR ${LMDB_DEPS_DIR}/libraries/liblmdb)
find_library(LMDB_LIBRARY NAMES lmdb.a lmdb PATHS ${LMDB_SOURCE_DIR} Release NO_DEFAULT_PATH)
if(NOT LMDB_LIBRARY)
    configure_file(cmake/in/lmdb.in ${LMDB_SOURCE_DIR}/CMakeLists.txt COPYONLY)
    execute_process(COMMAND ${CMAKE_COMMAND} -G "${CMAKE_GENERATOR}" . WORKING_DIRECTORY ${LMDB_SOURCE_DIR})
    execute_process(COMMAND ${CMAKE_COMMAND} --build . WORKING_DIRECTORY ${LMDB_SOURCE_DIR})
    find_library(LMDB_LIBRARY NAMES lmdb.a lmdb PATHS ${LMDB_SOURCE_DIR} Release NO_DEFAULT_PATH)
endif()
include_directories(${LMDB_SOURCE_DIR})