set(LIBUV_DEPS_DIR ${CMAKE_SOURCE_DIR}/deps/libuv)
find_library(LIBUV_LIBRARY NAMES uv_a.a uv PATHS ${LIBUV_DEPS_DIR} Release NO_DEFAULT_PATH)
if(NOT LIBUV_LIBRARY)
    execute_process(COMMAND ${CMAKE_COMMAND} -G "${CMAKE_GENERATOR}" . WORKING_DIRECTORY ${LIBUV_DEPS_DIR})
    execute_process(COMMAND ${CMAKE_COMMAND} --build . WORKING_DIRECTORY ${LIBUV_DEPS_DIR})
    find_library(LIBUV_LIBRARY NAMES uv_a.a libuv PATHS ${LIBUV_DEPS_DIR} Release NO_DEFAULT_PATH)
endif()
include_directories(${LIBUV_DEPS_DIR}/include)